name: synckit_example
description: "Example app demonstrating the synckit package"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  hive_ce: ^2.8.0
  hive_ce_flutter: ^2.1.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  fast_immutable_collections: ^11.0.0
  synckit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^3.0.4
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.7.0
  hive_ce_generator: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

